# Generated by Django 4.2 on 2023-04-16 23:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmetics',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cosmetics',
            name='passport',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='passport_pictures'),
        ),
        migrations.AlterField(
            model_name='cosmetics',
            name='colour',
            field=models.CharField(choices=[('red', 'red'), ('black', 'black'), ('nude', 'nude'), ('pink', 'pink'), ('brown', 'brown'), ('purple', 'purple'), ('white', 'white')], max_length=100),
        ),
    ]
